### PR TITLE
docs: add contributing and code of conduct

### PR DESCRIPTION
**Pull request by prydonius**

### CODE REVIEW

**Comment by prydonius** [comment]
cc @migmartri

**Comment by sebgoa** [comment]
maybe the Code of conduct shoudl refrence the CNCF code of conduct like core, even though this is not an official k8s project

**Comment by prydonius** [comment]
@sebgoa I copied this from https://github.com/kubernetes/kubernetes-template-project but it's not that up-to-date. I will update to https://github.com/kubernetes/kubernetes/blob/master/code-of-conduct.md

**Comment by prydonius** [comment]
@sebgoa updated PTAL

**Pull request merged**
