### PR TITLE
helm - bump mongodb requirement

### LINKED ISSUE #419: monocular CrashLoopBackOff with mongo in pending
I have installed monocular using helm and the pod seems to crashloop.
monogo db pod is in pending status. No logs in monogo pod.
Can some  guide where the issue is ?

monocular-mongodb-3297385788-2sf4d                    0/1       Pending            0          19m
monocular-monocular-api-4206649573-6pmm6              0/1       CrashLoopBackOff   8          19m
monocular-monocular-api-4206649573-vql6m              0/1       CrashLoopBackOff   8          19m
monocular-monocular-prerender-2060794013-n8k1v        1/1       Running            0          19m
monocular-monocular-ui-2374440452-rglv5               1/1       Running            0          19m
monocular-monocular-ui-2374440452-wwq7p               1/1       Running            0          19m
ngix-nginx-ingress-controller-593623324-wsnkt         1/1       Running            0          22m
ngix-nginx-ingress-default-backend-2369107551-j9253   1/1       Running            0          22m
ui-kubernetes-dashboard-2399210613-1tf6r              1/1       Running            0          20h

### PR DESCRIPTION
**Pull request by iam-merlin**
bump mongodb requirement to 4.0.4 and create a default database monocular

fix #419

### CODE REVIEW

**Comment by iam-merlin** [comment]
Simple bump version of mongodb. I also linked `Values.mongodb.mongodbDatabase` to `monocular.yaml/mongodb/database`.

Please review and check the deployment in your env (for example on AKS or GKE). 

FYI : I use nfs provisioner in my env.

**Comment by prydonius** [comment]
thanks @iam-merlin can you please bump the chart version in Chart.yaml too?

**Comment by prydonius** [comment]
perfect, you'll need to sign the CNCF CLA in order to get this approved!

**Comment by iam-merlin** [comment]
it's signed... was slow to appear here xD

**Pull request merged**
