### PR TITLE
Add truthiness check to arrayMatch

### LINKED ISSUE #614: Search is broken in some situations
The details are on https://github.com/helm/hub/issues/55

### PR DESCRIPTION
**Pull request by unguiculus**
Fixes #614 

Signed-off-by: Reinhard Nägele <unguiculus@gmail.com>

### CODE REVIEW

**Comment by scottrigby** [comment]
From keybase chat: 

I'm thinking since we can't control the structure of charts that are in repos defined for a monocular instance, we should decide how we want to handle charts with missing data. 

Perhaps we should clearly define which chart data is required and which is optional. One way to address this could be to validate chart data, at which time charts missing required data could be removed from listing/searching, etc (`getCharts()`/`getChart()`). And charts missing optional data could be checked before trying to match each data point in `searchCharts`?

I'm not set up to test this right now, but since search is broken right now, if this fixes that issue perhaps we should merge now and discuss a larger fix later (whether the above, or some other proposal)?

**Comment by unguiculus** [comment]
I agree with @scottrigby. This is a quick fix we should do anyways because I think a truthiness check makes sense here. But we need to collect requirements that must be met for charts to belisted.

**Comment by scottrigby** [comment]
So after a quick look with someone here, it seems the issue is we call `match()` on members without checking first whether they're undefined. This is the error @prydonius saw in https://github.com/helm/hub/issues/55#issuecomment-471666795:
>TypeError: Cannot read property 'match' of undefined

**Comment by scottrigby** [comment]
@unguiculus If that is correct ^ then perhaps we should do this instead? https://github.com/helm/monocular/pull/616 I need to run, so it was faster to just make a quick alternative PR. Can you take a look and see if this makes sense to you?

**Comment by prydonius** [comment]
I might be missing something, but this PR doesn't seem to fix the issue. It looks like we're just changing the order in which we check for whether `keywords` is defined. The problem, as I understood it, is `keywords` might be a defined array, but some of its elements could be `undefined`. This means that the `keyword` inside the `keywords.some` block fails the `.match` call. This PR doesn't appear to fix that, but @scottrigby's #616 does.

Let me know if I'm misunderstanding the issue though, I haven't tested either PR.

**Comment by prydonius** [comment]
cc @Dean-Coakley

**Comment by unguiculus** [comment]
@prydonius I see, you're probably right. I was just kind of quickly trying the fix what you described in https://github.com/helm/hub/issues/55 and got it wrong.

**Pull request closed without merging**
