### PR TITLE
add ROADMAP

### PR DESCRIPTION
**Pull request by prydonius**

### CODE REVIEW

**Comment by prydonius** [comment]
cc @migmartri @Angelmmiguel @sebgoa

**Comment by Angelmmiguel** [comment]
@prydonius should we map the items of this file to issues and create a board in projects? I think it more easy to update. We don't need to update this file every time we finish or update an issue

**Comment by prydonius** [comment]
@Angelmmiguel yeah I was planning on setting up milestones/project after merging. I think we can see this as more of a higher level document, it doesn't necessarily need to link to issues. It might also make sense to have this in the wiki instead. I based this off of https://github.com/kubernetes-incubator/service-catalog/wiki/Roadmap

**Comment by Angelmmiguel** [comment]
@prydonius I agree we can use the wiki. I think it's easier to update

**Comment by prydonius** [comment]
@Angelmmiguel I've moved this to the wiki https://github.com/helm/monocular/wiki/Roadmap

thanks!

**Comment by Angelmmiguel** [comment]
Thanks @prydonius!!

**Pull request closed without merging**
