### PR TITLE
Update chart resources apiVersion

### PR DESCRIPTION
**Pull request by Dean-Coakley**
Fixes: https://github.com/helm/monocular/issues/636

### Issue:
This is a required change to make the chart installable on Kubernetes 1.16.

### Proposed changes:
* Update all `Deployment` resources of the chart to `apps/v1` as required by Kubernetes 1.16
* Update `mongodb` chart dependency. From `4.6.2` -> `7.2.10`.
  * This was required because `mongodb:4.6.2` also used the deprecated `"extensions/v1beta1"` apiVersion.
* Add `spec.selector` as required by the new apiVersion.
  
  > Error: release monocular-dev failed: Deployment.apps "monocular-dev-monocular-ui" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"app":"monocular-dev-monocular-ui"}: `selector` does not match template `labels`]

#### Note: 
I did not increment the `version` of the chart. It looks like this is done via CI?

### CODE REVIEW

**Comment by Dean-Coakley** [comment]
@mattfarina @absoludity Are either of ye able to review/approve/merge?

**Comment by prydonius** [comment]
The CI only bumps the chart version if we have tagged a release for new code changes, but chart changes that aren't tied to a code release should manually bump the version. I think this is a non-breaking change, so we should bump the patch version of the chart here.

**Comment by Dean-Coakley** [comment]
@prydonius Sure. I wasn't certain if updating mongodb dep version was a breaking change.

Thanks for the review. I've bumped the patch version of the chart.

**Comment by Dean-Coakley** [comment]
Rebumped chart version 2 patches - under the assumption that #647 will be merged first

**Pull request merged**
