### PR TITLE
docs: Improve deployment documentation

### PR DESCRIPTION
**Pull request by prydonius**
- Show how to install Nginx Ingress Controller in README
- Document Ingress configuration in chart README
- Describe how to access Monocular in NOTES.txt based on various
  settings

cc @sebgoa

### CODE REVIEW

**Comment by sebgoa** [comment]
I followed it step by step on minikube and the "wheel keeps turning". the charts do not display.

**Comment by prydonius** [comment]
@sebgoa PTAL

**Comment by prydonius** [comment]
Thanks @sebgoa!

**Pull request merged**
