### PR TITLE
Use proxy env settings for Transport

### PR DESCRIPTION
**Pull request by ralfv**
Makes chart-repo use proxy environment settings as proposed in https://github.com/kubeapps/kubeapps/issues/696.

Signed-off-by: Ralf Van Dorsselaer <ralfvandorsselaer@gmail.com>

### CODE REVIEW

**Comment by prydonius** [comment]
@ralfv thanks a lot! Can you follow the instructions in https://github.com/helm/monocular/pull/595/checks to sign off your commit for acceptance?

**Comment by ralfv** [comment]
> @ralfv thanks a lot! Can you follow the instructions in https://github.com/helm/monocular/pull/595/checks to sign off your commit for acceptance?

I'm willing but the contribution instructions conflict with the DCO failed check. The contribution instructions describe to use the full name so I did but then that failed:

Commit sha: babe9a3, Author: ralfv, Committer: GitHub; Expected "ralfv ralfvandorsselaer@gmail.com", but got "Ralf Van Dorsselaer ralfvandorsselaer@gmail.com".

So what do I do now?

**Comment by prydonius** [comment]
@ralfv hmm looking at the commit (https://github.com/helm/monocular/commit/babe9a3f402ec658060d04b1e38a92708c424151.patch), the author is "ralfv" not "Ralf Van Dorsselaer". You could either amend the commit to change the author or change the Sign-Off to match the author name in the commit.

**Comment by prydonius** [comment]
Closing as #602 beat you to it - sorry you couldn't get the DCO fixed!

**Pull request closed without merging**
